### ISSUE TITLE
App Crash: on adding folder

### ISSUE THREAD

**Issue by abakhai** [mahbubiftekhar/Swipe-2-Sort-Public#6]
I installed the app and opened the app through the play store, I clicked a button to add a folder. I named the folder on the naming pop up, and I clicked on the add button. As soon as I clicked it the app crashed. When I opened the app again, the folder was there, with the name I had typed in. To make sure this was not a one of, I tried it again, and the app crashed at the same moment. 

Android API 26

**Comment by mahbubiftekhar** [comment]
Hi 

Thanks for reporting this issue, My apologies for this bug, I believe this issue has been resolved in recent updates. 

If you continue to experience any issues, please feel free to contact myself. 

Thanks, 

Mahbub
